### ISSUE TITLE
SpinTEvolve not working with OOMMF 2.1a0

### ISSUE THREAD

**Issue by samjrholt** [fangohr/oommf#55]
We get the following error when using `make build` with the newest version of OOMMF.

``` bash
/home/holtsamu/repos/oommf/oommf/app/oxs/local/anv-spintevolve-3d/spintevolve_3d.cc: In member function ‘void Anv_SpinTEvolve_3d::NegotiateTimeStep(const Oxs_TimeDriver*, const Oxs_SimState&, Oxs_SimState&, OC_REAL8m, OC_BOOL, OC_BOOL&, OC_BOOL&) const’:
/home/holtsamu/repos/oommf/oommf/app/oxs/local/anv-spintevolve-3d/spintevolve_3d.cc:815:39: error: no matching function for call to ‘Oxs_TimeDriver::FillStateSupplemental(Oxs_SimState&) const’
  815 |   driver->FillStateSupplemental(nstate);
      |                                       ^
In file included from /home/holtsamu/repos/oommf/oommf/app/oxs/local/anv-spintevolve-3d/spintevolve_3d.cc:19:
/home/holtsamu/repos/oommf/oommf/app/oxs/ext/timedriver.h:83:16: note: candidate: ‘virtual void Oxs_TimeDriver::FillStateSupplemental(const Oxs_SimState&, Oxs_SimState&) const’
   83 |   virtual void FillStateSupplemental(const Oxs_SimState& old_state,
      |                ^~~~~~~~~~~~~~~~~~~~~
/home/holtsamu/repos/oommf/oommf/app/oxs/ext/timedriver.h:83:16: note:   candidate expects 2 arguments, 1 provided
/home/holtsamu/repos/oommf/oommf/app/oxs/local/anv-spintevolve-3d/spintevolve_3d.cc: In member function ‘virtual OC_BOOL Anv_SpinTEvolve_3d::Step(const Oxs_TimeDriver*, Oxs_ConstKey<Oxs_SimState>, const Oxs_DriverStepInfo&, Oxs_Key<Oxs_SimState>&)’:
/home/holtsamu/repos/oommf/oommf/app/oxs/local/anv-spintevolve-3d/spintevolve_3d.cc:1838:20: error: ‘OC_UINT4m Oxs_DriverStepInfo::current_attempt_count’ is private within this context
 1838 |       && step_info.current_attempt_count==0)) {
      |                    ^~~~~~~~~~~~~~~~~~~~~
In file included from /home/holtsamu/repos/oommf/oommf/app/oxs/ext/timedriver.h:14,
                 from /home/holtsamu/repos/oommf/oommf/app/oxs/local/anv-spintevolve-3d/spintevolve_3d.cc:19:
/home/holtsamu/repos/oommf/oommf/app/oxs/base/driver.h:35:13: note: declared private here
   35 |   OC_UINT4m current_attempt_count;  // Number of attempts at current step
      |             ^~~~~~~~~~~~~~~~~~~~~
/home/holtsamu/repos/oommf/oommf/app/oxs/local/anv-spintevolve-3d/spintevolve_3d.cc:1838:20: note: field ‘OC_UINT4m Oxs_DriverStepInfo::current_attempt_count’ can be accessed via ‘OC_UINT4m Oxs_DriverStepInfo::GetCurrentAttemptCount() const’
 1838 |       && step_info.current_attempt_count==0)) {
      |                    ^~~~~~~~~~~~~~~~~~~~~
      |                    GetCurrentAttemptCount()
<55052> pimake 2.1a0  panic:
child process exited abnormally
1 Error(s) detected
make: *** [Makefile:19: build] Error 1
```

**Comment by fangohr** [comment]
Hm, the same error seems to be thrown for the 2.0b version (see https://github.com/fangohr/oommf/actions/runs/8025257539/job/21925491638). 

However, we have compiled this in the past, and it worked? At least we have Docker Images for version 2.0b online (see version log at https://github.com/fangohr/oommf/blob/7d739ece133b8a7a70c27f579c1131576dc93f46/versionlog.txt#L77 and Docker Image at https://hub.docker.com/r/oommf/oommf/tags (for both 2.0b and 2.0b-1).). 😕
